#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 31 14:02:30 2018

@author: yatingupta
"""

#Multiple Linear Regression

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# importing dataset

#x are independent variables that is the first 3
#y is dependent variable that is purchased

dataset = pd.read_csv('50_Startups.csv')
x = dataset.iloc[:,:-1].values
#[:,:-1] left means taking all the rows and right means taking all columns -1
y = dataset.iloc[:,4].values

# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
x[:, 3] = labelencoder_X.fit_transform(x[:, 3])
onehotencoder = OneHotEncoder(categorical_features = [3])
x = onehotencoder.fit_transform(x).toarray()

#Avoiding the dummy variable trap
x = x[:,1:]

#splitting dataset into traning set and test set
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)
#fitting multiple regression to training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

#Predicitng the test results
y_pred = regressor.predict(x_test)

#building the optimal model using backward elimination
import statsmodels.formula.api as sm

#including x0 variable with constant
x = np.append(arr = np.ones((50,1)).astype(int) ,values = x,axis = 1)#Adding a column with only ones in it
x_opt = x[:,[0,1,2,3,4,5]]
regressor_OLS = sm.OLS(endog = y,exog = x_opt).fit()
regressor_OLS.summary()
#Checking if P > significaNCE VALUE
#Removing index 2
x_opt = x[:,[0,1,3,4,5]]
regressor_OLS = sm.OLS(endog = y,exog = x_opt).fit()
regressor_OLS.summary()

#Removing index 1
x_opt = x[:,[0,3,4,5]]
regressor_OLS = sm.OLS(endog = y,exog = x_opt).fit()
regressor_OLS.summary()

 #Removing index 4
x_opt = x[:,[0,3,5]]
regressor_OLS = sm.OLS(endog = y,exog = x_opt).fit()
regressor_OLS.summary()

 #Removing index 5
x_opt = x[:,[0,3]]
regressor_OLS = sm.OLS(endog = y,exog = x_opt).fit()
regressor_OLS.summary()




